name: "Greet Action"
description: "A simple GitHub Action to greet someone"
branding:
  icon: "smile"
  color: "blue"

inputs:
  who-to-greet:
    description: "Name of the person to greet"
    required: true
    default: "World"

outputs:
  time:
    description: "The time we greeted"

runs:
  using: "node16"
  main: "index.js"
