name: Test Custom Action

on:
  push:
    branches:
      - main

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd .github/actions/greet-action
          npm install

      - name: Run custom action
        id: greet
        uses: ./.github/actions/greet-action
        with:
          who-to-greet: Yogesh
